name: Build Spring Boot App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Verify Java Version
        run: java -version

      - name: Build Project
        run: mvn clean install

      - name: List Generated JAR
        run: ls -l target/

      - name: Build Docker Image
        run: docker build -t task-scheduler .